### ISSUE TITLE
Storing Private Files

### ISSUE THREAD

**Issue by pawloaka** [fsi-open/files#43]
My `fsi_files.yaml` looks like:
```yaml
fsi_files:
    url_adapters:
        public: 'fsi_files.url_adapter.public'
        private: 'fsi_files.url_adapter.private'
    entities:
        App\User:
            filesystem: 'private'
            prefix: user
            fields:
                - { name: profile }
```
`oneup_flysystem.yaml` looks like:
```yaml
oneup_flysystem:
    adapters:
        public_adapter:
            local:
                directory: '%kernel.project_dir%/public/uploads'
        private_adapter:
            local:
                directory: '%kernel.project_dir%/var/uploads'
    filesystems:
        public_filesystem:
            adapter: public_adapter
            mount: public_filesystem
        private_filesystem:
            adapter: private_adapter
            mount: private_filesystem
```

`services.yaml` looks like:
```yaml
...
  fsi_files.url_adapter.public:
    class: FSi\Component\Files\UrlAdapter\BaseUrlAdapter
    arguments:
      $uriFactory: '@Psr\Http\Message\UriFactoryInterface'
      $baseUrl: 'https://localhost/uploads/'

  fsi_files.url_adapter.private:
    class: FSi\Component\Files\UrlAdapter\BaseUrlAdapter
    arguments:
      $uriFactory: '@Psr\Http\Message\UriFactoryInterface'
      $baseUrl: 'https://localhost/private/uploads/'
...
```
And now my question is how to access from the web these private files stored in `%kernel.project_dir%/var/uploads`?
Should I make a special controller which is listening on `https://localhost/private/uploads/`? If yes, how it should look like?
