### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by pawloaka** [fsi-open/files#44]
Hi, 
is it possible to upload, download, check if exists a file on the FTP server with your bundle?
If yes, how? May you upload the config file that will show how to connect to ftp server?

**Comment by pawloaka** [comment]
I have tried something like this:
```yaml

oneup_flysystem:
    adapters:
        ftp_adapter:
            ftp:
                host: 'ftp.example.com'
                username: 'username'
                password: 'password'
                port: 21
                root: '/path/to/root'
                passive: true
                ssl: true
                timeout: 30
    filesystems:
        ftp_filesystem:
            adapter: ftp_adapter
            mount: ftp_filesystem


fsi_files:
    url_adapters:
        ftp: 'fsi_files.url_adapter.ftp'
    entities:
        App\User:
            filesystem: 'ftp'
            prefix: user
            fields:
                - { name: photo }

#services.yaml
...
  fsi_files.url_adapter.ftp:
    class: FSi\Component\Files\UrlAdapter\BaseUrlAdapter
    arguments:
      $uriFactory: '@Psr\Http\Message\UriFactoryInterface'
      $baseUrl: 'What's here?'
```
